language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t talekien1710/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true talekien1710/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-460960373806"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  # http://dockerreact-env.eba-wqdnzmgp.us-east-2.elasticbeanstalk.com/
