version: "3"
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: . # where files pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # not map this inside container
      - .:/app # map . outside container to /app inside container


  # Not too ideal
  # tests:
  #   build:
  #     context: . # where files pulled from
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules # not map this inside container
  #     - .:/app # map . outside container to /app inside container
  #   command: ["npm", "run", "test"]

  # docker-compose -f docker-compose-dev.yml up: dev environment
